name: Release to PyPI

on:
  release:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
    types: [released, prereleased]

jobs:
  release:
    name: Release on Pypi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Package and Upload
        env:
          STACKMANAGER_VERSION: ${{ github.event.release.tag_name }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
